In [1]:
users = spark.read('data/ml-1m/users.dat')

TypeError: 'DataFrameReader' object is not callable

In [3]:
usersrdd = sc.textFile('data/ml-1m/users.dat')

In [5]:
movies_rdd = sc.textFile('data/ml-1m/movies.dat')

In [6]:
ratings_rdd = sc.textFile('data/ml-1m/ratings.dat')

In [7]:
usersrdd.count()

6040

In [9]:
usersrdd.show()

AttributeError: 'RDD' object has no attribute 'show'

In [10]:
usersrdd.first()

'1::F::1::10::48067'

In [11]:
def split_to_columns(text):
    return text.split("::")

In [13]:
user_rows = usersrdd.map(split_to_columns)

In [17]:
user_df = spark.createDataFrame(user_rows,schema=['user_id','gender','age','job','pin'])

In [22]:
rating_df = spark.createDataFrame(ratings_rdd.map(lambda x:x.split("::")),schema=['user_id','movie_id','rating','timestamp'])

In [20]:
movie_df = spark.createDataFrame(movies_rdd.map(lambda x:x.split("::")),schema=['movie_id','title','genre'])

In [24]:
user_df.join(rating_df,on="user_id").collect()

[Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1250', rating='3', timestamp='974931632'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='2997', rating='3', timestamp='974931925'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='589', rating='4', timestamp='974930654'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='593', rating='3', timestamp='974930569'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1287', rating='4', timestamp='974931632'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1293', rating='4', timestamp='974931575'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='908', rating='3', timestamp='974930672'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='909', rating='3', timestamp='974931763'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='912', rating='4', timestamp='974931647'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='913', rating='3', timestamp='974932091'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='923', rating='3', timestamp='974931727'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='924', rating='3', timestamp='974931710'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='2268', rating='4', timestamp='974931188'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='3219', rating='2', timestamp='974932144'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='2273', rating='4', timestamp='974932415'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='2428', rating='2', timestamp='974932031'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='953', rating='3', timestamp='974931805'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='954', rating='4', timestamp='974931710'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='2433', rating='3', timestamp='974931961'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='3095', rating='3', timestamp='974931519'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1645', rating='4', timestamp='974932391'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='2605', rating='3', timestamp='974932031'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1673', rating='3', timestamp='974930715'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='3450', rating='3', timestamp='974930654'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='3623', rating='3', timestamp='974930851'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='2683', rating='1', timestamp='974931925'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='2688', rating='1', timestamp='974932050'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1894', rating='1', timestamp='974932292'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='434', rating='4', timestamp='974930873'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='296', rating='5', timestamp='974930775'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='454', rating='3', timestamp='974931397'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='608', rating='4', timestamp='974931168'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='480', rating='5', timestamp='974930521'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='628', rating='3', timestamp='974931311'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='648', rating='4', timestamp='974930851'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='805', rating='3', timestamp='974931360'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1193', rating='4', timestamp='974930590'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='3101', rating='3', timestamp='974930590'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='832', rating='2', timestamp='974930890'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='2324', rating='5', timestamp='974931111'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1393', rating='4', timestamp='974931269'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='3307', rating='3', timestamp='974931486'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1704', rating='4', timestamp='974931168'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1569', rating='4', timestamp='974930542'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='100', rating='3', timestamp='974932362'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='3176', rating='3', timestamp='974932221'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1573', rating='4', timestamp='974930824'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1580', rating='4', timestamp='974930654'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='110', rating='3', timestamp='974931168'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1584', rating='4', timestamp='974931311'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1730', rating='4', timestamp='974931360'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='3198', rating='3', timestamp='974931591'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='2396', rating='2', timestamp='974932179'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='2546', rating='3', timestamp='974931981'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='150', rating='3', timestamp='974931188'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='2710', rating='2', timestamp='974931944'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='3386', rating='3', timestamp='974931247'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='318', rating='5', timestamp='974931111'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1939', rating='3', timestamp='974931632'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='2762', rating='5', timestamp='974932196'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='2763', rating='4', timestamp='974932221'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1961', rating='4', timestamp='974931608'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='36', rating='3', timestamp='974931207'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='2770', rating='3', timestamp='974931944'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='47', rating='4', timestamp='974932277'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='50', rating='5', timestamp='974930802'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1208', rating='3', timestamp='974931677'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1213', rating='3', timestamp='974931111'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1221', rating='4', timestamp='974931519'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='2028', rating='4', timestamp='974931128'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1093', rating='3', timestamp='974932004'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1246', rating='4', timestamp='974931727'),
 Row(user_id='1090', gender='M', age='25', job='7', pin='94105', movie_id='1247', rating='4', timestamp='974931662'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='3793', rating='3', timestamp='974864430'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2054', rating='3', timestamp='974864750'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='587', rating='1', timestamp='974863880'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='589', rating='4', timestamp='974864329'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='737', rating='1', timestamp='974865059'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='592', rating='4', timestamp='974864068'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1270', rating='3', timestamp='974864366'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='748', rating='2', timestamp='974865059'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='3033', rating='3', timestamp='974863951'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2091', rating='1', timestamp='974864968'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='924', rating='4', timestamp='974864329'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='780', rating='2', timestamp='974864874'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='788', rating='3', timestamp='974864750'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1603', rating='2', timestamp='974864839'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2288', rating='3', timestamp='974864366'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2455', rating='3', timestamp='974864477'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1653', rating='2', timestamp='974864508'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2456', rating='1', timestamp='974864806'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1676', rating='1', timestamp='974864718'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2628', rating='3', timestamp='974863737'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1831', rating='2', timestamp='974865059'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1690', rating='1', timestamp='974864940'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2640', rating='3', timestamp='974864477'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2641', rating='2', timestamp='974864682'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2642', rating='1', timestamp='974865027'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2808', rating='2', timestamp='974865027'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1862', rating='1', timestamp='974865166'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1863', rating='1', timestamp='974863521'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2668', rating='2', timestamp='974865000'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='3471', rating='3', timestamp='974864329'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2672', rating='3', timestamp='974865000'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1876', rating='3', timestamp='974864682'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='260', rating='5', timestamp='974863776'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2827', rating='2', timestamp='974865090'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1882', rating='1', timestamp='974865166'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2699', rating='3', timestamp='974864636'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2858', rating='4', timestamp='974864154'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1127', rating='3', timestamp='974864430'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1129', rating='4', timestamp='974864508'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='611', rating='1', timestamp='974865116'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='3698', rating='3', timestamp='974864806'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='480', rating='3', timestamp='974864430'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2105', rating='3', timestamp='974864682'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1320', rating='3', timestamp='974864839'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1321', rating='3', timestamp='974864202'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='3863', rating='3', timestamp='974864839'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1196', rating='5', timestamp='974864284'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1199', rating='4', timestamp='974864329'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1356', rating='3', timestamp='974864554'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2311', rating='2', timestamp='974864554'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1371', rating='2', timestamp='974864905'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1372', rating='3', timestamp='974864636'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1373', rating='1', timestamp='974865116'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1375', rating='2', timestamp='974864718'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1376', rating='2', timestamp='974864508'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1377', rating='3', timestamp='974864068'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='849', rating='3', timestamp='974864940'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2322', rating='2', timestamp='974865116'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2329', rating='3', timestamp='974864154'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='852', rating='1', timestamp='974863521'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1391', rating='3', timestamp='974864839'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1544', rating='2', timestamp='974864968'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='3156', rating='1', timestamp='974864636'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='880', rating='1', timestamp='974865090'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='3300', rating='2', timestamp='974864554'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1562', rating='1', timestamp='974864068'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='3175', rating='3', timestamp='974864611'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1573', rating='2', timestamp='974864477'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='3328', rating='4', timestamp='974863880'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1580', rating='4', timestamp='974864477'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2392', rating='1', timestamp='974863483'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1590', rating='3', timestamp='974865027'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1591', rating='3', timestamp='974865090'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2549', rating='1', timestamp='974865116'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1748', rating='3', timestamp='974864430'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='3354', rating='1', timestamp='974865027'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2701', rating='1', timestamp='974865116'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2706', rating='2', timestamp='974864154'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1909', rating='3', timestamp='974864611'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='153', rating='2', timestamp='974864068'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2571', rating='5', timestamp='974864329'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1917', rating='1', timestamp='974864750'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='160', rating='1', timestamp='974865166'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1779', rating='1', timestamp='974864968'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='163', rating='3', timestamp='974863521'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='2722', rating='2', timestamp='974864940'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1921', rating='2', timestamp='974864477'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='3527', rating='3', timestamp='974864397'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1924', rating='4', timestamp='974864905'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='316', rating='3', timestamp='974864682'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='173', rating='2', timestamp='974865090'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='3535', rating='4', timestamp='974864202'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='329', rating='2', timestamp='974864718'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='1019', rating='3', timestamp='974864682'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='24', rating='1', timestamp='974864611'),
 Row(user_id='1159', gender='M', age='18', job='0', pin='48314', movie_id='29', rating='3', timestamp='974864366'),